export const productTypeList = [
  {
    id: 1,
    title: "Cashews & Pine Nuts",
    img: "img/1.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#FDF0E3",
    alt: "Молочный",
  },
  {
    id: 2,
    title: "Cranberry",
    img: "img/2.png",
    info: "Состав: молочный шоколад, клюква",
    type: "Темный",
    color: "#fff",
    bgColor: "#401F19",
    alt: "Темный",
  },
  {
    id: 3,
    title: "Ginger & Pine Nuts",
    img: "img/3.png",
    info: "Состав: молочный шоколад, имбирь, кедровые орехи",
    type: "Double",
    color: "#fff",
    bgColor: "#401F19",
    alt: "Double",
  },
  {
    id: 4,
    title: "Cashews & Pine Nuts",
    img: "img/4.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#fff",
    bgColor: "#AE4A84",
    alt: "Mix",
  },
  {
    id: 5,
    title: "Cranberry",
    img: "img/5.png",
    info: "Состав: молочный шоколад, клюква",
    type: "Special",
    color: "#fff",
    bgColor: "#F1B647",
    alt: "Special",
  },
];

export const productList = [
  {
    id: 1,
    title: "dates",
    img: "img/products/milk/dates.png",
    info: "Состав: шоколад молочный, финики Аджва, миндаль, соль Гималайская",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 2,
    title: "pistachios",
    img: "img/products/milk/pistachios.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 3,
    title: "salted Almond",
    img: "img/products/milk/Salted almond.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 4,
    title: "walnut and Raisins",
    img: "img/products/milk/Walnut and raisins.png",
    info: "Состав: шоколад тёмный, грецкие орехи, киш-миш",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 5,
    title: "dates dark",
    img: "img/products/dark/dates dark.png",
    info: "Состав: шоколад тёмный, финики Аджва, миндаль, соль Гималайская",
    type: "Темный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Темный",
  },
  {
    id: 6,
    title: "pistachios dates",
    img: "img/products/dark/pistachios dark.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Темный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Темный",
  },
  {
    id: 7,
    title: "salted almond dark",
    img: "img/products/dark/Salted almond dark.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Темный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Темный",
  },
  {
    id: 8,
    title: "walnut and raisins dark",
    img: "img/products/dark/Walnut and raisins dark.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Темный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Темный",
  },
  {
    id: 9,
    title: "apricot and pistachios",
    img: "img/products/double/Apricot and pistachios.png",
    info: "Состав: шоколад молочный, шоколад тёмный, фисташки, курага",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 10,
    title: "coconut and pecan",
    img: "img/products/double/Coconut and pecan.png",
    info:
      "Состав: шоколад молочный, шоколад тёмный, кокос сушёный, орехи пекан",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 11,
    title: "mango and walnut",
    img: "img/products/double/Mango and walnut.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 12,
    title: "passion fruit and walnut",
    img: "img/products/double/Passion fruit and walnut.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 13,
    title: "pecan and prunes",
    img: "img/products/double/Pecan and prunes.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 14,
    title: "pineapple & walnut",
    img: "img/products/double/Pine apple & walnut.png",
    info:
      "Состав: шоколад молочный, шоколад тёмный, грецкие орехи, ананас сушёный",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 15,
    title: "waffles",
    img: "img/products/double/Waffles.png",
    info: "Состав: шоколад молочный, шоколад тёмный, вафли, орехи пекан",
    type: "Double",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Double",
  },
  {
    id: 16,
    title: "dessert",
    img: "img/products/mixed/dessert.png",
    info:
      "Состав: шоколад молочный, шоколад Gold, творог, сливки, клубника, фисташки, орехи пекан, киш-миш",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 17,
    title: "HOT",
    img: "img/products/mixed/hot.png",
    info: "Состав: шоколад тёмный, острый перец, миндаль, соль Гималайская",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 18,
    title: "New Line",
    img: "img/products/mixed/new line.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 19,
    title: "truffles",
    img: "img/products/mixed/truffel.png",
    info: "Состав: шоколад тёмный, шоколад Ruby, какао, соль Гималайская",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 20,
    title: "gold",
    img: "img/products/special/gold.png",
    info: "Состав: шоколад Gold, миндаль, соль Гималайская",
    type: "Special",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Special",
  },
  {
    id: 21,
    title: "ruby",
    img: "img/products/special/ruby.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Special",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Special",
  },
];
