export const productTypeList = [
  {
    id: 1,
    title: "Cashews & Pine Nuts",
    img: "img/1.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 2,
    title: "Cranberry",
    img: "img/2.png",
    info: "Состав: молочный шоколад, клюква",
    type: "Черный",
    color: "#fff",
    bgColor: "#401f19",
    alt: "Черный",
  },
  {
    id: 3,
    title: "Ginger & Pine Nuts",
    img: "img/3.png",
    info: "Состав: молочный шоколад, имбирь, кедровые орехи",
    type: "Двойной",
    color: "#fff",
    bgColor: "#e7b15b",
    alt: "Двойной",
  },
  {
    id: 4,
    title: "Cashews & Pine Nuts",
    img: "img/4.png",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#fff",
    bgColor: "#ef88a5",
    alt: "Mix",
  },
  {
    id: 5,
    title: "Cranberry",
    img: "img/5.png",
    info: "Состав: молочный шоколад, клюква",
    type: "Special",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Special",
  },
];

export const productList = [
  {
    id: 1,
    title: "Dates",
    img: "img/products/milk/dates.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 2,
    title: "Pistachios",
    img: "img/products/milk/pistachios.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 3,
    title: "Salted Almond",
    img: "img/products/milk/Salted almond.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 4,
    title: "Walnut and Raisins",
    img: "img/products/milk/Walnut and raisins.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Молочный",
  },
  {
    id: 5,
    title: "Dates Dark",
    img: "img/products/dark/dates dark.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Черный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Черный",
  },
  {
    id: 6,
    title: "Pistachios Dates",
    img: "img/products/dark/pistachios dark.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Черный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Черный",
  },
  {
    id: 7,
    title: "Salted Almond Dark",
    img: "img/products/dark/Salted almond dark.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Черный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Черный",
  },
  {
    id: 8,
    title: "Walnut and Raisins Dark",
    img: "img/products/dark/Walnut and raisins dark.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Черный",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Черный",
  },
  {
    id: 9,
    title: "Apricot and Pistachios",
    img: "img/products/double/Apricot and pistachios.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 10,
    title: "Coconut and Pecan",
    img: "img/products/double/Coconut and pecan.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 11,
    title: "Mango and Walnut",
    img: "img/products/double/Mango and walnut.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 12,
    title: "Passion Fruit and Walnut",
    img: "img/products/double/Passion fruit and walnut.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 13,
    title: "Pecan and Prunes",
    img: "img/products/double/Pecan and prunes.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 14,
    title: "Pineapple & Walnut",
    img: "img/products/double/Pine apple & walnut.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 15,
    title: "Waffles",
    img: "img/products/double/Waffles.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Двойной",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Двойной",
  },
  {
    id: 16,
    title: "Dessert",
    img: "img/products/mixed/dessert.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 17,
    title: "Hot",
    img: "img/products/mixed/hot.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 18,
    title: "New Line",
    img: "img/products/mixed/new line.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 19,
    title: "Truffel",
    img: "img/products/mixed/truffel.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Mix",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Mix",
  },
  {
    id: 20,
    title: "Gold",
    img: "img/products/special/gold.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Special",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Special",
  },
  {
    id: 21,
    title: "Ruby",
    img: "img/products/special/ruby.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Special",
    color: "#333",
    bgColor: "#fdebdb",
    alt: "Special",
  },
];
