export const productTypeList = [
  {
    id: 1,
    title: "Cashews & Pine Nuts",
    img: "img/products/1.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#333",
    bgColor: "#fdebdb",
  },
  {
    id: 2,
    title: "Cranberry",
    img: "img/products/2.jpg",
    info: "Состав: молочный шоколад, клюква",
    type: "Черный",
    color: "#fff",
    bgColor: "#401f19",
  },
  {
    id: 3,
    title: "Ginger & Pine Nuts",
    img: "img/products/3.jpg",
    info: "Состав: молочный шоколад, имбирь, кедровые орехи",
    type: "Руби",
    color: "#fff",
    bgColor: "#e7b15b",
  },
  {
    id: 4,
    title: "Cashews & Pine Nuts",
    img: "img/products/1.jpg",
    info: "Состав: молочный шоколад, кешью, кедровые орехи",
    type: "Молочный",
    color: "#fff",
    bgColor: "#ef88a5",
  },
  {
    id: 5,
    title: "Cranberry",
    img: "img/products/2.jpg",
    info: "Состав: молочный шоколад, клюква",
    type: "Черный",
    color: "#333",
    bgColor: "#fdebdb",
  },
];
